---
# tasks file for newrelic_wsgi


#    https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-admin-script
- name: create directory for newrelic config
  file:
    dest=/opt/newrelic/
    mode=755
    state=directory
  sudo: yes
 
- name: pip install newrelic
  pip: name=newrelic
  sudo: yes

- name: generate ini
  shell: /usr/local/bin/newrelic-admin generate-config {{newrelic_license_key}} {{newrelic_ini_file}} 
  sudo: yes

- name: modify python newrelic.ini license
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="license_key =" line="license_key = {{newrelic_license_key}}"
  sudo: yes

# lineinfile only replaces the last matching lines; use replace instead
- name: modify python newrelic.ini app name
  replace: dest={{newrelic_ini_file}} regexp='.*app_name =.*\n' replace="app_name = {{application_name}}\n"
  sudo: yes

- name: modify python newrelic.ini high security on
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="high_security =" line="high_security = true"
  sudo: yes

- name: modify python newrelic.ini logfile
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="log_file =" line="newrelic.logfile = {{newrelic_agentlog_file}}"
  sudo: yes

- name: add agent config to the wsgi file
  lineinfile: dest={{wsgi_scriptfile}} state=present line="newrelic.agent.initialize('{{newrelic_ini_file}}')" insertbefore=BOF
  sudo: yes

- name: import newrelic to wsgi
  lineinfile: dest={{wsgi_scriptfile}} state=present line="import newrelic.agent" insertbefore=BOF
  sudo: yes
  notify:
    - restart apache
  
#    /usr/local/bin/newrelic-admin validate-config  /opt/newrelic/newrelic.ini



    
    
