---
# tasks file for newrelic_wsgi


#    https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-admin-script
- name: create directory for newrelic config
  file:
    dest=/opt/newrelic/
    mode=755
    state=directory
  sudo: yes

- name: create directory for newrelic logging accessible to apache user
  file:
    dest={{newrelic_agentlog_path}}
    mode=755
    owner=apache
    group=apache
    state=directory
  sudo: yes
 
- name: pip install newrelic
  pip: name=newrelic
       extra_args='--install-option="--install-scripts=/usr/bin"'
  sudo: yes

- name: use newrelic-admin to generate ini
  command: newrelic-admin generate-config {{newrelic_license_key}} {{newrelic_ini_file}}
  sudo: yes

# lineinfile only replaces the last matching lines; use replace for multiple app_name replaces
- name: modify python newrelic.ini app name
  replace: dest={{newrelic_ini_file}} regexp='.*app_name =.*\n' replace="app_name = {{application_name}}\n"
  sudo: yes

- name: modify python newrelic.ini high security on
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="high_security =" line="high_security = true"
  sudo: yes

- name: modify python newrelic.ini logfile
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="log_file =" line="log_file = {{newrelic_agentlog_file}}"
  sudo: yes

- name: add agent config to the wsgi file
  lineinfile: dest={{wsgi_scriptfile}} state=present line="newrelic.agent.initialize('{{newrelic_ini_file}}')" insertbefore=BOF
  sudo: yes

- name: import newrelic to wsgi
  lineinfile: dest={{wsgi_scriptfile}} state=present line="import newrelic.agent" insertbefore=BOF
  sudo: yes
  notify:
    - restart apache
