---
# defaults file for newrelic_wsgi
newrelic_ini_path: /opt/newrelic/
newrelic_agentlog_path: /tmp
newrelic_ini_file: "{{newrelic_ini_path}}/newrelic.ini"
newrelic_agentlog_file: "{{newrelic_agentlog_path}}/newrelic_python_agent.log"
application_name: "Python App1"
newrelic_high_security: true
