---
# Provisions a VM with a New Relic agent

- hosts: php-app
  gather_facts: False
  roles:
    - python27
    - apache
    - mysql
    - php
    - newrelic_php

- hosts: python-app
  gather_facts: False
  roles:
    - python27
    - apache
    - wsgi_app
    - newrelic_wsgi
