---
# defaults file for newrelic_php
newrelic_inifile: /opt/newrelic/newrelic_php.ini
newrelic_agent_logfile: /tmp/newrelic-php-agent.log
python_application_name: "PHP App1"
newrelic_high_security: true
