---
# tasks file for newrelic_php

- name: install rpm
  yum: name=rpm
  sudo: yes

- name: use rpm to get new relic yum repo
  shell: rpm -Uvh http://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
  sudo: yes
  ignore_errors: yes

- name: yum install newrelic php agent
  yum: name=newrelic-php5
  sudo: yes

- name: configure a php agent
  shell: export NR_INSTALL_SILENT=true; /usr/bin/newrelic-install install
  sudo: yes
  notify:
    - restart apache

- name: modify php newrelic.ini license
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="newrelic.license =" line="newrelic.license = {{newrelic_license_key}}"
  sudo: yes

- name: modify php newrelic.ini app name
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="newrelic.appname =" line="newrelic.appname = {{application_name}}"
  sudo: yes

- name: modify php newrelic.ini high security on
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="newrelic.high_security =" line="newrelic.high_security = 1"
  sudo: yes

- name: modify php newrelic.ini logfile
  lineinfile: dest={{newrelic_ini_file}} state=present regexp="newrelic.logfile =" line="newrelic.logfile = {{newrelic_agentlog_file}}"
  sudo: yes
  notify:
    - restart apache
